export const RoleTypes = {
  LOAD_REQUEST: '@role/LOAD_REQUEST',
  LOAD_SUCCCES: '@role/LOAD_SUCCCES',
  LOAD_FAILURE: '@role/LOAD_FAILURE',

  CREATE_ROLE_REQUEST: '@role/CREATE_ROLE_REQUEST',
  CREATE_ROLE_SUCCESS: '@role/CREATE_ROLE_SUCCESS',

  DELETE_ROLE_REQUEST: '@role/DELETE_ROLE_REQUEST',
  DELETE_ROLE_SUCCESS: '@role/DELETE_ROLE_SUCCESS',

  SELECT_ROLE_UPDATE: '@role/SELECT_ROLE_UPDATE',
  UPDATE_ROLE_REQUEST: '@role/UPDATE_ROLE_REQUEST',
  UPDATE_ROLE_SUCCESS: '@role/UPDATE_ROLE_SUCCESS'
};
