export const AuthTypes = {
  SIGN_IN_REQUEST: '@auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: '@auth/LOAD_FAILURE',
  SIGN_OUT_REQUEST: '@auth/SIGN_OUT_REQUEST'
};
